//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_ProductCategories { get; set; }
        public string name { get; set; }
        public string Fvailibility { get; set; }
        public Nullable<int> Price { get; set; }
        public string sostav { get; set; }
        public string Decor { get; set; }
        public string Length { get; set; }
        public string vstavka { get; set; }
        public string Insert { get; set; }
        public string Features { get; set; }
        public string Type_of_Clasp { get; set; }
        public string Insole_material { get; set; }
        public string Path_the_foto { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
