//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int Id { get; set; }
        public int Id_user { get; set; }
        public int Id_product { get; set; }
        public int Count { get; set; }
        public bool Closed { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
